Right panel redesign
uz0/chatter.io pull request #177
Opened 2019-08-27 11:15 UTC by danilstoyanov

2019-08-27 11:16 UTC, dcversus commented on src/components/button/index.js
> +  {...disabled ? { disabled: true } : {}}
ого конструкция ХД

2019-08-27 11:17 UTC, dcversus reviewed
Что это еще за fake-select / fake-checkbox Воу воу!! Почему нельзя юзать обычные с несуществующими полями?

2019-08-27 11:18 UTC, dcversus commented on src/components/panel_container/index.js
> +    const peopleCollapseText = this.props.details.group.is_space ? `${this.props.details.group.participants.length} members` : this.props.t('people');
дай `this.props.details.group.participants.length` имя и вынеси в константу, а то сложно читается(

2019-08-27 11:18 UTC, dcversus commented on src/components/panel_container/index.js
> +                  peopleDropdownItems.push({ text: this.props.t('message'), onClick: () => this.goToChatByUserId(user.id) });
вообще тут бы переносы строк в обьекте поставить (и ниже также)

2019-08-27 11:27 UTC, danilstoyanov commented on src/components/panel_container/index.js
> +    const peopleCollapseText = this.props.details.group.is_space ? `${this.props.details.group.participants.length} members` : this.props.t('people');
Согласен, поправил

2019-08-27 11:31 UTC, danilstoyanov commented on src/components/panel_container/index.js
> +                  peopleDropdownItems.push({ text: this.props.t('message'), onClick: () => this.goToChatByUserId(user.id) });
Готово

2019-08-27 11:35 UTC, efim1382 commented
> Что это еще за fake-select / fake-checkbox Воу воу!! Почему нельзя юзать обычные с несуществующими полями?

они нужны потом в components/form что б в редюкс загонять значения. Эти со стейтом, components/form/checkbox с редьюксом, components/form/checkbox использует fake-checkbox, и его же можно использовать в любом месте

2019-08-27 12:56 UTC, efim1382 requested changes

2019-08-27 12:56 UTC, efim1382 commented on src/components/panel_container/style.css
>  .panel > .scroll > .collapse {
![image](https://user-images.githubusercontent.com/13278088/63770959-f201a600-c8de-11e9-954f-daf6f56c06ca.png)

тут отступ должен быть

как на макете
![image](https://user-images.githubusercontent.com/13278088/63770877-c7175200-c8de-11e9-9a2a-e926dca477a8.png)

2019-08-27 12:56 UTC, efim1382 commented on src/components/panel_container/style.css
> +.panel > .scroll > .select {
![image](https://user-images.githubusercontent.com/13278088/63771229-689ea380-c8df-11e9-8722-ba40d68c4540.png)
убери фокус

2019-08-27 12:56 UTC, efim1382 commented on src/components/panel_container/style.css
> +.panel > .actions .close {
На макетах кнопка 38 пикселей

2019-08-27 12:56 UTC, efim1382 commented on src/components/panel_container/style.css
> +  padding-bottom: 30px;
![image](https://user-images.githubusercontent.com/13278088/63771455-db0f8380-c8df-11e9-8b1d-d46c19857f0a.png)
у тебя нижний паддинг заезжает на середину блока. 

а если паддинги убрать, то высота блока не соответствует внутреннему контенту
![image](https://user-images.githubusercontent.com/13278088/63771826-8e787800-c8e0-11e9-87b9-5399facb26c7.png)


я писал, что когда есть родитель с флексами, а у него есть дочерние элементы + 1 большой, растянутый с flex-grow: 1, то остальным нужно ставить flex-shrink: 0

![export](https://user-images.githubusercontent.com/13278088/63772383-a7355d80-c8e1-11e9-954e-5a695066827c.png)

2019-08-27 12:56 UTC, efim1382 commented on src/components/panel_container/style.css
> +  --label-color: #252c43;
не нужно ее создавать. Это глобальный цвет --text-color

2019-08-27 12:56 UTC, efim1382 commented on src/components/panel_container/style.css
> +  margin-left: var(--layout-padding);
Это делать паддингами

2019-08-27 12:56 UTC, efim1382 commented on src/components/panel_container/style.css
> +  --text-color: #252c43;
не нужно создавать эти цвета, ты переопределяешь глобальные переменные, они уже существуют

2019-08-27 12:56 UTC, efim1382 commented on src/components/panel_container/style.css
> +  height: var(--height);
Откуда тут --height, где она обьявлена?

2019-08-27 12:56 UTC, efim1382 commented on src/components/panel_container/style.css
> +  --divider-color: #f3f4f7;
Он уже существует, не надо переопределять

2019-08-27 12:56 UTC, efim1382 commented on src/components/fake-select/style.css
> +  --color: #9ca0b0;
Иконка на макете серая.
И на будущее, цвет #9ca0b0 - это глобальный var(--text-color)

2019-08-27 12:56 UTC, efim1382 commented on src/components/fake-select/style.css
> +.container select {
![image](https://user-images.githubusercontent.com/13278088/63773091-1c556280-c8e3-11e9-83c2-16363212f6b8.png)

если будет длинное слово, все поедет и накроет иконку

2019-08-27 15:45 UTC, danilstoyanov commented on src/components/button/index.js
> +  {...disabled ? { disabled: true } : {}}
тогда в доме будет disabled={false} и он иногда false игнорит и все равно читает как disable (c) Роман

2019-08-27 16:58 UTC, danilstoyanov commented on src/components/panel_container/style.css
>  .panel > .scroll > .collapse {
Исправил

2019-08-27 17:03 UTC, danilstoyanov commented on src/components/panel_container/style.css
> +.panel > .scroll > .select {
Пофиксил

2019-08-27 17:05 UTC, danilstoyanov commented on src/components/panel_container/style.css
> +.panel > .actions .close {
Пофиксил

2019-08-27 17:08 UTC, danilstoyanov commented on src/components/panel_container/style.css
> +  padding-bottom: 30px;
пофиксил

2019-08-27 17:12 UTC, danilstoyanov commented on src/components/panel_container/style.css
> +  margin-left: var(--layout-padding);
Пофиксил

2019-08-27 17:13 UTC, danilstoyanov commented on src/components/panel_container/style.css
> +  height: var(--height);
копипаст скорее всего, убрал

2019-08-28 09:03 UTC, danilstoyanov commented on src/components/fake-select/style.css
> +.container select {
Пофиксил

2019-08-28 09:10 UTC, danilstoyanov commented on src/components/panel_container/style.css
> +  --label-color: #252c43;
+

2019-08-28 09:11 UTC, danilstoyanov commented on src/components/panel_container/style.css
> +  --text-color: #252c43;
Пофиксил

2019-08-28 09:12 UTC, danilstoyanov commented on src/components/panel_container/style.css
> +  --divider-color: #f3f4f7;
Пофиксил

2019-08-28 09:13 UTC, danilstoyanov commented on src/components/fake-select/style.css
> +  --color: #9ca0b0;
Пофиксил

2019-08-28 09:32 UTC, merged